import = [
    "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.normal]
family = "Hack Nerd Font Mono"

[window]
decorations = "Buttonless"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9
