config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_zshrc.d:
    src: zshrc.d
    dst: ~/.zshrc.d
profiles:
  mac:
    dotfiles:
    - f_zshrc
    - d_zshrc.d
