config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_zshrc.d:
    src: zshrc.d
    dst: ~/.zshrc.d
    link: link_children
  d_pip:
    src: pip
    dst: ~/.pip
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  d_vim:
    src: vim
    dst: ~/.vim
    link: link_children
    upignore:
    - "autoload"
    - "plugged"
    - ".netrwhist"
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_spacemacs.d:
    src: spacemacs.d
    dst: ~/.spacemacs.d
  d_aria2:
    src: aria2
    dst: ~/.aria2
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  d_i3:
    src: config/i3
    dst: ~/.config/i3
profiles:
  mac:
    variables:
      aria2_alloc: prealloc
    dotfiles:
    - f_zshrc
    - d_zshrc.d
    - d_pip
    - f_vimrc
    - d_vim
    - d_nvim
    - d_spacemacs.d
    - d_aria2
  arch:
    include:
    - mac
    variables:
      aria2_alloc: falloc
    dotfiles:
    - f_xinitrc
    - f_xresources
    - d_i3
