config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_zshrc.d:
    src: zshrc.d
    dst: ~/.zshrc.d
    link: link_children
  d_pip:
    src: pip
    dst: ~/.pip
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  d_vim:
    src: vim
    dst: ~/.vim
    link: link_children
    upignore:
    - autoload
    - plugged
    - .netrwhist
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_spacemacs.d:
    src: spacemacs.d
    dst: ~/.spacemacs.d
  d_aria2:
    src: aria2
    dst: ~/.aria2
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  f_isort.cfg:
    src: isort.cfg
    dst: ~/.isort.cfg
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_fontconfig:
    src: config/fontconfig
    dst: ~/.config/fontconfig
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  f_gpg-agent.conf:
    src: gnupg/gpg-agent.conf
    dst: ~/.gnupg/gpg-agent.conf
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
profiles:
  mac:
    variables:
      aria2_alloc: prealloc
    dotfiles:
    - f_zshrc
    - d_zshrc.d
    - d_pip
    - f_vimrc
    - d_vim
    - d_nvim
    - d_spacemacs.d
    - d_aria2
    - f_isort.cfg
    - d_alacritty
    - f_tmux.conf
    - f_gpg-agent.conf
    - f_p10k.zsh
  arch:
    include:
    - mac
    variables:
      aria2_alloc: falloc
    dotfiles:
    - f_xinitrc
    - f_xresources
    - d_i3
    - d_fontconfig
    - d_polybar
    - f_xmodmap
