config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_zshrc.d:
    src: zshrc.d
    dst: ~/.zshrc.d
  d_pip:
    src: pip
    dst: ~/.pip
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_spacemacs.d:
    src: spacemacs.d
    dst: ~/.spacemacs.d
profiles:
  mac:
    dotfiles:
    - f_zshrc
    - d_zshrc.d
    - d_pip
    - f_vimrc
    - d_nvim
    - d_spacemacs.d
